# Generated by Django 3.2.4 on 2021-06-17 23:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20210617_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 23, 11, 23, 614871, tzinfo=utc)),
        ),
    ]
